name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Auto Create Flutter App Structure
        run: |
          # প্রথমে একটি টেম্পোরারি ফোল্ডারে ফুল ফ্লাটার প্রজেক্ট তৈরি করবে
          flutter create --platforms=android my_tmp_app
          
          # আমাদের মেইন ফাইলগুলো ওই প্রজেক্টে ট্রান্সফার করবে
          cp main.dart my_tmp_app/lib/main.dart
          cp pubspec.yaml my_tmp_app/pubspec.yaml
          
          # এবার মূল ডিরেক্টরিতে প্রজেক্টের সব ফাইল নিয়ে আসবে
          mv my_tmp_app/* .
          mv my_tmp_app/.* . 2>/dev/null || true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cyber-elite-panel-app
          path: build/app/outputs/flutter-apk/app-release.apk
